# Generated by scripts/release (handup) for v0.1.2. Do not edit.
cask "handup" do
  name "handup"
  desc "Approval inbox for AI agents"
  homepage "https://gethandup.dev"
  version "0.1.2"

  livecheck do
    skip "Updated by the handup release."
  end

  binary "handup"

  on_macos do
    on_intel do
      url "https://github.com/gethandup/handup/releases/download/v0.1.2/handup_0.1.2_darwin_amd64.tar.gz"
      sha256 "01bbc4b00b5f7c0dce16ad97ff7bac54af73a005f446b07559fbcd0c68531ef3"
    end
    on_arm do
      url "https://github.com/gethandup/handup/releases/download/v0.1.2/handup_0.1.2_darwin_arm64.tar.gz"
      sha256 "bb530b829fe2e196780bb37474689aff6b386e38202299b4a6410caf6d74fc00"
    end
  end

  # Keep share/handup/web beside the staged binary: handup resolves its real path.

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/handup"]
    end
  end

  caveats do
    "Run `handup setup` to start handup and connect your agents. The binary is not notarized."
  end
end
