# Generated by scripts/release (handup) for v0.1.1. Do not edit.
cask "handup" do
  name "handup"
  desc "Approval inbox for AI agents"
  homepage "https://gethandup.dev"
  version "0.1.1"

  livecheck do
    skip "Updated by the handup release."
  end

  binary "handup"

  on_macos do
    on_intel do
      url "https://github.com/gethandup/handup/releases/download/v0.1.1/handup_0.1.1_darwin_amd64.tar.gz"
      sha256 "fd308beea6138e7622508207ad0eb5ee033fd4e39a932a72a39ce320346964aa"
    end
    on_arm do
      url "https://github.com/gethandup/handup/releases/download/v0.1.1/handup_0.1.1_darwin_arm64.tar.gz"
      sha256 "2d0c258ff28fc5f284398cfcac516cb088758235e404c5bb63218ff6f28ab867"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/handup"]
    end
  end

  caveats do
    "Run `handup setup` to start handup and connect your agents. The binary is not notarized."
  end
end
