# Generated by scripts/release (handup) for v0.1.6. Do not edit.
cask "handup" do
  name "handup"
  desc "Approval inbox for AI agents"
  homepage "https://gethandup.dev"
  version "0.1.6"

  livecheck do
    skip "Updated by the handup release."
  end

  binary "handup"

  on_macos do
    on_intel do
      url "https://github.com/gethandup/handup/releases/download/v0.1.6/handup_0.1.6_darwin_amd64.tar.gz"
      sha256 "5fb5c2a023a4d56b9789d6b060f06036685e288e70d793915272bf0b18b7c48a"
    end
    on_arm do
      url "https://github.com/gethandup/handup/releases/download/v0.1.6/handup_0.1.6_darwin_arm64.tar.gz"
      sha256 "2be562017558aa76cc9b8168ab35a1fafe4a7bf0e3316a567a234c686d402e8e"
    end
  end

  # Keep share/handup/web beside the staged binary: handup resolves its real path.

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/handup"]
    end
  end

  caveats do
    "Run `handup setup` to start handup and connect your agents. The binary is not notarized."
  end
end
